### PR TITLE
#63 fix and test

### LINKED ISSUE #63: Wrintig crash on dtype problems
```
ddf = tfs.TfsDataFrame([[1, 2.], [3, 4.]], columns=['int', 'float'])
tfs.write_tfs('fdfsdf.tfs', ddf)

ddf
   int  float
0    1    2.0
1    3    4.0
```

crashes with 

```
ValueError: Unknown format code 'd' for object of type 'float'
```

- [ ] WHY????
- [ ] fix
- [ ] TEST

### PR DESCRIPTION
**Pull request by JoschD**
Fixes #63

### CODE REVIEW

**Comment by JoschD** [comment]
As to the why:
```
data_frame.apply(lambda series: format_strings.format(*series), axis=1)
```
extracts rows as Series. If all elements in the DataFrame are numeric and there is a float, 
the Series will be of `dtype='float64'` and hence integers will be converted, causing the bug,
as the `format_strings` expects an integer.

This bug was not discovered before, because we always have a non-numeric (e.g. string) column,
then the extracted Series will be of `dtype=object` and each element keeps their own dtype.

**Comment by fsoubelet** [comment]
Can you include a test with a column-less dataframe as the example provided in #62?

```python
    def test_write_int_float_no_column_names(self, _test_file: str):
        df = tfs.TfsDataFrame(data=[[1, 2.], [3, 4.]])
        write_tfs(_test_file, df)
        new = read_tfs(_test_file)
        assert_frame_equal(df, new)
```

**Comment by JoschD** [comment]
> Can you include a test with a column-less dataframe as the example provided in #62?
> 
> ```python
>     def test_write_int_float_no_column_names(self, _test_file: str):
>         df = tfs.TfsDataFrame(data=[[1, 2.], [3, 4.]])
>         write_tfs(_test_file, df)
>         new = read_tfs(_test_file)
>         assert_frame_equal(df, new)
> ```

? But this is for #62

**Comment by fsoubelet** [comment]
Bakc when I though we were doing I PR for both

**Review by fsoubelet — APPROVED** [review]

**Pull request merged**
